name: mood_tune
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cloud_firestore: ^6.1.2
  equatable: ^2.0.8
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  injectable: ^2.7.1+4
  json_annotation: ^4.11.0
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  injectable_generator: ^2.12.0

flutter:
  uses-material-design: true
